--loadstring:
--loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/hub.lua",true))() 
--Uses Kavo UI Library
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-Ui-Library/main/source.lua"))() 
local Window = Library.CreateLib("ChipLag Hub", "DarkTheme")

--Universal
local universal = Window:NewTab("Universal")
local uUniversal = universal:NewSection("UNIVERSAL SCRIPTS")
uUniversal:NewButton("[NEW] AdmFreeze", "Detect Frozen Roblox Admin Players!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/universal/Admfreeze.lua",true))() 
end) 
uUniversal:NewButton("StickyScript", "Make yourself stuck at a postition", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/universal/sticky.lua",true))() 
end) 
uUniversal:NewButton("StickyFlight", "Make yourself stuck at a postition and be able to fling others", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/universal/stickyfling.lua",true))() 
end) 
uUniversal:NewButton("Security Cameras (BUGGY)", "Script for Security Cameras to spy on people", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/universal/securitycam.lua",true))()
end)
uUniversal:NewButton("Simple Infinite Jump", "Its just a Part Glued to your foot with a delay so you can fall", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ChipLag/rb/main/universal/simpleinfjump.lua",true))()
end) 

local uUseful = universal:NewSection("USEFUL UNIVERSAL SCRIPTS NOT BY ME")
uUseful:NewButton("Nameless Admin", "Nameless Admin", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FilteringEnabled/NamelessAdmin/main/Source"))() 
end) 
uUseful:NewButton("Infinite Yield", "An Absolute Classic! ", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
